NUM_TRACKS = 3
NUM_BANKS = 3
NUM_CONTROLS = 4

RECORD_CONTROL = 0
STOP_CONTROL = 1
UNDO_CONTROL = 2
CLEAR_CONTROL = 3

RESET_COMMAND = 0
INSTANCE_CHANGE = 6

ABLETON_CONNECTED_COMMAND = 0
CHANGE_STATE_COMMAND = 1
REQUEST_CONTROL_COMMAND = 2
DOWNBEAT_COMMAND = 3
CHANGE_BANK_COMMAND = 7

NOTE_TYPE = 0

DATALOOPER_KEY = 'DL#'
CLIPLOOPER_KEY = 'CL#'
TRACK_KEYS = [DATALOOPER_KEY, CLIPLOOPER_KEY]

NOTE_OFF_STATUS = 128
NOTE_ON_STATUS = 144
CC_STATUS = 176

# QUANTIZE VALUES
GLOBAL = 0.0
NO_QUANTIZATION = 1.0
EIGHT_BARS = 2.0
FOUR_BARS = 3.0
TWO_BARS = 4.0
ONE_BAR = 5.0
HALF_NOTE = 6.0
HALF_TRIPLET = 7.0
QUARTER_NOTE = 8.0
QUARTER_TRIPLET = 9.0
EIGHTH_NOTE = 10.0
EIGHTH_TRIPLET = 11.0
SIXTEENTH_NOTE = 12.0
SIXTEENTH_NOTE_TRIPLET = 13.0
THIRTY_SECOND_NOTE = 14.0

# LOOPER PARAMS
DEVICE_ON = 0
STATE = 1

STOP_STATE = 0
RECORDING_STATE = 1
PLAYING_STATE = 2
OVERDUB_STATE = 3
CLEAR_STATE = 4
OFF_STATE = 5
NEW_SESSION_STATE = 6
CONFIG_STATE = 7
DISARMED_STATE = 8

FEEDBACK = 2
REVERSE = 3
MONITOR = 4
SPEED = 5
QUANTIZATION = 6
SONG_CONTROL = 7

NO_TEMPO_CONTROL = 0
FOLLOW_SONG_TEMPO = 1
SET_AND_FOLLOW_SONG_TEMPO = 2

TEMPO_CONTROL = 8

ANY_VALUE = -1
LONG_PRESS = 2
RELEASE = 1
PRESS = 0

LOOPER_TRACK = 0
CLIP_TRACK = 1
BOTH_TRACK_TYPES = 2

LOOPER_MODE = 0
NEW_SESSION_MODE = 1

OFF = 0
ON = 1
TOGGLE = 2

DELETE_CLIP = 0
NEW_SCENE_KEEP_PLAYING = 1
NEW_SCENE_STOP = 2
STOP_CLIP = 3

LOOPER_ACTIONS = {
    0 : 'record',
    1 : 'stop',
    2 : 'undo',
    3 : 'clear',
    4 : 'toggle_mute',
    5 : 'get_new_clip_slot'
}